# Generated by Django 4.1.7 on 2023-03-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='picture/%Y/%m/%d/'),
        ),
    ]
