# Generated by Django 4.1.1 on 2023-04-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_alter_post_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
    ]
